### PR TITLE
- Added Puppet Parser Validate support

### PR DESCRIPTION
**Pull request by pjmagee**
- Settings for location of parser and puppet exe/bat files
- If path contains spaces, wrap it in '"' for cp.spawn
- converted tmLanguage to tmLanguage.json for easier navigation
- Added -> syntax support because i was losing some syntax highlighting
- There still seems to be a minor syntax highlight problem when using a defined resource.

### CODE REVIEW

**Comment by pjmagee** [comment]
This CI build error doesn't look like it's fixable from the PR.

**Comment by dschaaff** [comment]
You may want to look at putting this against https://github.com/bitzl/vscode-puppet. That fork seems to be getting ongoing development while this one does not.

**Comment by pjmagee** [comment]
This is now merged on the other Repository.

**Comment by dschaaff** [comment]
Awesome!

**Pull request closed without merging**
